/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	storageiov1alpha1 "github.com/tommenx/hdfs-operator/pkg/apis/storage.io/v1alpha1"
	versioned "github.com/tommenx/hdfs-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tommenx/hdfs-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tommenx/hdfs-operator/pkg/client/listers/storage.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HdfsClusterInformer provides access to a shared informer and lister for
// HdfsClusters.
type HdfsClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HdfsClusterLister
}

type hdfsClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHdfsClusterInformer constructs a new informer for HdfsCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHdfsClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHdfsClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHdfsClusterInformer constructs a new informer for HdfsCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHdfsClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha1().HdfsClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha1().HdfsClusters(namespace).Watch(options)
			},
		},
		&storageiov1alpha1.HdfsCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *hdfsClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHdfsClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hdfsClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storageiov1alpha1.HdfsCluster{}, f.defaultInformer)
}

func (f *hdfsClusterInformer) Lister() v1alpha1.HdfsClusterLister {
	return v1alpha1.NewHdfsClusterLister(f.Informer().GetIndexer())
}
