/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tommenx/hdfs-operator/pkg/apis/storage.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHdfsClusters implements HdfsClusterInterface
type FakeHdfsClusters struct {
	Fake *FakeStorageV1alpha1
	ns   string
}

var hdfsclustersResource = schema.GroupVersionResource{Group: "storage.io", Version: "v1alpha1", Resource: "hdfsclusters"}

var hdfsclustersKind = schema.GroupVersionKind{Group: "storage.io", Version: "v1alpha1", Kind: "HdfsCluster"}

// Get takes name of the hdfsCluster, and returns the corresponding hdfsCluster object, and an error if there is any.
func (c *FakeHdfsClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hdfsclustersResource, c.ns, name), &v1alpha1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HdfsCluster), err
}

// List takes label and field selectors, and returns the list of HdfsClusters that match those selectors.
func (c *FakeHdfsClusters) List(opts v1.ListOptions) (result *v1alpha1.HdfsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hdfsclustersResource, hdfsclustersKind, c.ns, opts), &v1alpha1.HdfsClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HdfsClusterList{ListMeta: obj.(*v1alpha1.HdfsClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.HdfsClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hdfsClusters.
func (c *FakeHdfsClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hdfsclustersResource, c.ns, opts))

}

// Create takes the representation of a hdfsCluster and creates it.  Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *FakeHdfsClusters) Create(hdfsCluster *v1alpha1.HdfsCluster) (result *v1alpha1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hdfsclustersResource, c.ns, hdfsCluster), &v1alpha1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HdfsCluster), err
}

// Update takes the representation of a hdfsCluster and updates it. Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *FakeHdfsClusters) Update(hdfsCluster *v1alpha1.HdfsCluster) (result *v1alpha1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hdfsclustersResource, c.ns, hdfsCluster), &v1alpha1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HdfsCluster), err
}

// Delete takes name of the hdfsCluster and deletes it. Returns an error if one occurs.
func (c *FakeHdfsClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hdfsclustersResource, c.ns, name), &v1alpha1.HdfsCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHdfsClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hdfsclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HdfsClusterList{})
	return err
}

// Patch applies the patch and returns the patched hdfsCluster.
func (c *FakeHdfsClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hdfsclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HdfsCluster), err
}
