/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/tommenx/hdfs-operator/pkg/apis/storage.io/v1alpha1"
	scheme "github.com/tommenx/hdfs-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HdfsClustersGetter has a method to return a HdfsClusterInterface.
// A group's client should implement this interface.
type HdfsClustersGetter interface {
	HdfsClusters(namespace string) HdfsClusterInterface
}

// HdfsClusterInterface has methods to work with HdfsCluster resources.
type HdfsClusterInterface interface {
	Create(*v1alpha1.HdfsCluster) (*v1alpha1.HdfsCluster, error)
	Update(*v1alpha1.HdfsCluster) (*v1alpha1.HdfsCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.HdfsCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.HdfsClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HdfsCluster, err error)
	HdfsClusterExpansion
}

// hdfsClusters implements HdfsClusterInterface
type hdfsClusters struct {
	client rest.Interface
	ns     string
}

// newHdfsClusters returns a HdfsClusters
func newHdfsClusters(c *StorageV1alpha1Client, namespace string) *hdfsClusters {
	return &hdfsClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hdfsCluster, and returns the corresponding hdfsCluster object, and an error if there is any.
func (c *hdfsClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.HdfsCluster, err error) {
	result = &v1alpha1.HdfsCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hdfsclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HdfsClusters that match those selectors.
func (c *hdfsClusters) List(opts v1.ListOptions) (result *v1alpha1.HdfsClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HdfsClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hdfsclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hdfsClusters.
func (c *hdfsClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hdfsclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hdfsCluster and creates it.  Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *hdfsClusters) Create(hdfsCluster *v1alpha1.HdfsCluster) (result *v1alpha1.HdfsCluster, err error) {
	result = &v1alpha1.HdfsCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hdfsclusters").
		Body(hdfsCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hdfsCluster and updates it. Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *hdfsClusters) Update(hdfsCluster *v1alpha1.HdfsCluster) (result *v1alpha1.HdfsCluster, err error) {
	result = &v1alpha1.HdfsCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hdfsclusters").
		Name(hdfsCluster.Name).
		Body(hdfsCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the hdfsCluster and deletes it. Returns an error if one occurs.
func (c *hdfsClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hdfsclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hdfsClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hdfsclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hdfsCluster.
func (c *hdfsClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HdfsCluster, err error) {
	result = &v1alpha1.HdfsCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hdfsclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
